name: SinkLibrary
version: ${project.version.formatted}
description: Library required for Sink Plugins. This does nothing without a plugin that uses it.
author: [Trojaner, _ShadowRaven_]
website: http://static-interface.de
main: de.static_interface.sinklibrary.SinkLibrary
soft-depend: [Vault]

permissions:
  sinklibrary.bypassvanish:
     default: op

  sinklibrary.command.sinkreload:
     default: op

  sinklibrary.command.debug:
     default: op